services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    restart: on-failure
    volumes:
      - mariadb:/var/www/wordpress
    env_file:
      - ./requirements/mariadb/conf/.mariadb.env
